### ISSUE TITLE
Client ends silently when cannot connect to server

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#126]
When client cannot connect to server, it drops with traceback in the console output, but without anything said within client itself. Traceback:
```
Traceback (most recent call last):
  File "./outerspace.py", line 234, in <module>
    task(options)
  File "/home/dahaic/github/dahaic/outerspace/client/main_client.py", line 411, in runClient
    loginDlg.display(message = e.args[0])
  File "/home/dahaic/github/dahaic/outerspace/client/osci/dialog/LoginDlg.py", line 76, in display
    self.autoLogin()
  File "/home/dahaic/github/dahaic/outerspace/client/osci/dialog/LoginDlg.py", line 88, in autoLogin
    self.doLogin(gameID,login,password)
  File "/home/dahaic/github/dahaic/outerspace/client/osci/dialog/LoginDlg.py", line 100, in doLogin
    result = client.login(gameID, login, password)
  File "/home/dahaic/github/dahaic/outerspace/client/osci/client.py", line 75, in login
    cmdProxy.connect(login)
  File "/home/dahaic/github/dahaic/outerspace/server/lib/igeclient/IClient.py", line 68, in connect
    raise IClientException('Cannot connect to the server.')
igeclient.IClient.IClientException: Cannot connect to the server.
```

**Comment by dahaic** [comment]
Reproduction of this bug is not as straightforward as originally anticipated. Moving outside of milestones.
