### ISSUE TITLE
When resolution is set wrong, game does not start anymore

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#154]
On linux, it is reproducible by selecting fullscreen and selecting too large resolution. Result is traceback and abrupt end of the program.

```
Traceback (most recent call last):
  File "./outerspace.py", line 234, in <module>
    task(options)
  File "/home/dahaic/outerspace/client/main_client.py", line 265, in runClient
    screen = pygame.display.set_mode(gdata.scrnSize, flags, bestdepth)
pygame.error: No video mode large enough for 1920x2015
```
There is no trivial way to fix the mistake or revert back. Proposal is to in such case revert to default, with stretch goal - to print info message as the first dialog.

**Comment by dahaic** [comment]
Fixed by trying with default 800x600 resolution in case of problems.
