### ISSUE TITLE
Scrapping design fails due to global queue evaluation

### ISSUE THREAD

**Issue by dahaic** [ospaceteam/outerspace#67]
```
-------------------------------------------------------------------------------
2017-05-29 19:00:52 WAR -- Cannot complete RPC call
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ospace/.ospace/server/lib/ige/RPCServer.py", line 60, in call
    packet.result, packet.messages = apply(callMap[intern(packet.method)], params)
  File "/home/ospace/.ospace/server/lib/ige/GameMngr.py", line 396, in execute
    result = apply(cmdObj, (tran, obj) + args)
  File "/home/ospace/.ospace/server/lib/ige/ospace/IPlayer.py", line 518, in scrapShipDesign
    for taskID in xrange(len(queue)):
NameError: global name 'queue' is not defined
-------------------------------------------------------------------------------
```

**Comment by dahaic** [comment]
Still not fully functional
```
Traceback (most recent call last):
  File "/home/dahaic/github/dahaic/outerspace/server/lib/ige/RPCServer.py", line 60, in call
    packet.result, packet.messages = apply(callMap[intern(packet.method)], params)
  File "/home/dahaic/github/dahaic/outerspace/server/lib/ige/GameMngr.py", line 396, in execute
    result = apply(cmdObj, (tran, obj) + args)
  File "/home/dahaic/github/dahaic/outerspace/server/lib/ige/ospace/IPlayer.py", line 523, in scrapShipDesign
    self.cmd(obj).abortGlobalConstruction(queueID, taskID)
TypeError: abortGlobalConstruction() takes exactly 5 arguments (3 given)

```

**Comment by dahaic** [comment]
```
Traceback (most recent call last):
  File "/home/dahaic/github/dahaic/outerspace/server/lib/ige/RPCServer.py", line 60, in call
    packet.result, packet.messages = apply(callMap[intern(packet.method)], params)
  File "/home/dahaic/github/dahaic/outerspace/server/lib/ige/GameMngr.py", line 396, in execute
    result = apply(cmdObj, (tran, obj) + args)
  File "/home/dahaic/github/dahaic/outerspace/server/lib/ige/ospace/IPlayer.py", line 522, in scrapShipDesign
    if obj.prodQueues[queueID][taskID].techID == designID:
IndexError: list index out of range
```
